export { default as ArrowLeftIcon } from './ArrowLeftIcon.vue'
export { default as CloseIcon } from './CloseIcon.vue'
export { default as DownloadIcon } from './DownloadIcon.vue'
export { default as FileTextIcon } from './FileTextIcon.vue'
export { default as UploadIcon } from './UploadIcon.vue'
