export const CAMPAIGN_PERFORMANCE_BAR_DATASET_STYLE = {
  borderWidth: 1,
  borderRadius: 2,
} as const;

export const CAMPAIGN_PERFORMANCE_DONUT_DATASET_STYLE = {
  borderWidth: 2,
} as const;

export const CAMPAIGN_PERFORMANCE_DONUT_HIGHLIGHT_LIMIT = 7;
export const CAMPAIGN_PERFORMANCE_DONUT_DIM_THRESHOLD = 0.035;
export const CAMPAIGN_PERFORMANCE_DONUT_HIGHLIGHT_ALPHA = 1;
export const CAMPAIGN_PERFORMANCE_DONUT_SECONDARY_ALPHA = 0.8;
export const CAMPAIGN_PERFORMANCE_DONUT_DIM_ALPHA = 0.52;
