export const ROI_BUDGET_SCALING_POINT_RADIUS = 5;
export const ROI_BUDGET_SCALING_HIGHLIGHTED_POINT_RADIUS = 8;
export const ROI_BUDGET_SCALING_MIN_CAMPAIGNS = 5;
export const ROI_BUDGET_SCALING_BUDGET_AXIS_ROUNDING = 1000;
export const ROI_BUDGET_SCALING_TICK_VALUES = [-0.5, 0, 1, 5] as const;
